server {
    listen 80; #порт для nginx
    ai_news localhost; #имя сервера
    root /usr/share/nginx/html; #корневая директория
    index index.html; #файл по умолчанию
    location / {
        try_files $uri $uri/ /index.html; #попытка найти файл или директорию
    }
}